name: Daily Rate Fetch

on:
  schedule:
    # Run Monday-Friday at 11:00 AM EST (16:00 UTC) - when MND updates rates
    - cron: '0 16 * * 1-5'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  fetch-rates:
    runs-on: ubuntu-latest
    
    steps:
      - name: Fetch Latest Mortgage Rates
        run: |
          echo "🔄 Fetching mortgage rates from MND at $(date)"
          
          response=$(curl -s -w "HTTPSTATUS:%{http_code}" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            "${{ secrets.SUPABASE_URL }}/functions/v1/rate-fetch")
          
          # Extract HTTP status code
          http_code=$(echo $response | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
          
          # Extract response body
          body=$(echo $response | sed -e 's/HTTPSTATUS\:.*//g')
          
          echo "HTTP Status: $http_code"
          echo "Response: $body"
          
          # Check if request was successful
          if [ $http_code -eq 200 ]; then
            echo "✅ Successfully fetched rates at $(date)"
            
            # Parse and display rate summary
            echo "$body" | jq -r '
              if .success then
                "📊 Rate Summary:",
                "• Rates fetched: \(.rates_fetched)",
                "• Message: \(.message)"
              else
                "❌ Error: \(.error)"
              end
            '
          else
            echo "❌ Rate fetch failed with status $http_code at $(date)"
            echo "Response: $body"
            exit 1
          fi

      - name: Notify on Failure
        if: failure()
        run: |
          echo "🚨 Daily rate fetch failed at $(date)"
          echo "Please check the Supabase function logs at:"
          echo "${{ secrets.SUPABASE_URL }}/project/_/logs/edge-functions"